## ** Numpy Array Operations: **

In [6]:
import numpy as np

# Create the 1D NumPy array for Week 1 temperatures

temperature_w1 = np.array([22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9])
print(f"Temperatures of week 1 in Celsius: {temperature_w1}")

Temperatures of week 1 in Celsius: [22.5 25.3 20.8 23.4 26.1 24.8 21.9]


In [7]:
# Inspect the shape, data type, and the number of elements in the array. Inspect the shape of the temperatures_w1 array. 

print("Shape:",temperature_w1.shape)
print("Data Type:",temperature_w1.dtype)
print("Number of Elements:",temperature_w1.size)

Shape: (7,)
Data Type: float64
Number of Elements: 7


In [8]:
# Convert the temperatures_w1 from Celsius to Fahrenheit using the formula: 
# Fahrenheit = (Celsius * 9/5) + 32 

temperature_w1_f = (temperature_w1 * 9/5) + 32
print(f"Temperatures of week 1 in Fahrenheit: {temperature_w1_f}")

#Find the maximum, minimum, and mean temperatures for the week.

max_temp = temperature_w1_f.max()
print(f"Maximum Temperature: {max_temp:.2f}°F")
min_temp = temperature_w1_f.min()
print(f"Minimum Temperature: {min_temp:.2f}°F")
mean_temp = temperature_w1_f.mean()
print(f"Mean Temperature: {mean_temp:.2f}°F")

Temperatures of week 1 in Fahrenheit: [72.5  77.54 69.44 74.12 78.98 76.64 71.42]
Maximum Temperature: 78.98°F
Minimum Temperature: 69.44°F
Mean Temperature: 74.38°F


In [9]:
# Temperatures for the first three days of the week.

print("First three days:",temperature_w1_f[:3])

# Temperatures for the weekend (last two days).

print("Weekend days:",temperature_w1_f[-2:])

# temperatures for the  middle three days of the week.

print("Middle three days:",temperature_w1_f[2:5])

First three days: [72.5  77.54 69.44]
Weekend days: [76.64 71.42]
Middle three days: [69.44 74.12 78.98]


In [10]:
# Create a 2D NumPy array named temperatures where each row represents temperatures for a different week:  
# ★ Row 1: [22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9] (Week 1)  
# ★ Row 2: [19.2, 22.5, 21.3, 24.0, 23.5, 22.8, 20.1] (Week 2) 

temperatures = np.array([
    [22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9],  # Row 0: Week 1
    [19.2, 22.5, 21.3, 24.0, 23.5, 22.8, 20.1]   # Row 1: Week 2
])
print(f"Temperatures of two weeks: {temperatures}")

Temperatures of two weeks: [[22.5 25.3 20.8 23.4 26.1 24.8 21.9]
 [19.2 22.5 21.3 24.  23.5 22.8 20.1]]


In [11]:
# Inspect the temperatures Array:

print("Shape:",temperatures.shape)
print("Data Type:",temperatures.dtype)
print("Number of Elements:",temperatures.size)

temperatures_f = (temperatures * 9/5) + 32
print(f"Temperatures of two weeks in Fahrenheit: {temperatures_f}")

max_temp_2weeks = temperatures_f.max()
print(f"Maximum Temperature: {max_temp_2weeks:.2f}°F")
min_temp_2weeks = temperatures_f.min()
print(f"Minimum Temperature: {min_temp_2weeks:.2f}°F")
mean_temp_2weeks = temperatures_f.mean()
print(f"Mean Temperature: {mean_temp_2weeks:.2f}°F")

Shape: (2, 7)
Data Type: float64
Number of Elements: 14
Temperatures of two weeks in Fahrenheit: [[72.5  77.54 69.44 74.12 78.98 76.64 71.42]
 [66.56 72.5  70.34 75.2  74.3  73.04 68.18]]
Maximum Temperature: 78.98°F
Minimum Temperature: 66.56°F
Mean Temperature: 72.91°F


In [12]:
# Slice the temperatures Array:

print("Week 1 temperatures:",temperatures_f[0, :])
print("Weekend temperatures of Week 1:",temperatures_f[0, -2:])
print("Week 2 temperatures:",temperatures_f[1, :])
print("Weekend temperatures of Week 2:",temperatures_f[1, -2:])

Week 1 temperatures: [72.5  77.54 69.44 74.12 78.98 76.64 71.42]
Weekend temperatures of Week 1: [76.64 71.42]
Week 2 temperatures: [66.56 72.5  70.34 75.2  74.3  73.04 68.18]
Weekend temperatures of Week 2: [73.04 68.18]


## ** Pandas Series **

In [26]:
# Creating Pandas Series:  

import pandas as pd
import numpy as np
# ● Create a Pandas Series named marks with the following data:  
# ➢ Marks: 95, 92, 89, 85, 80  
# ➢ Custom Indices: 'Rank1', 'Rank2', 'Rank3', 'Rank4', 'Rank5'  

marks = np.array([95, 92, 89, 85, 80])
indices = ['Rank1', 'Rank2', 'Rank3', 'Rank4', 'Rank5']
ranks = pd.Series(data = marks, index = indices)
print(ranks)

Rank1    95
Rank2    92
Rank3    89
Rank4    85
Rank5    80
dtype: int64


In [27]:
# Indexing and Slicing:  
#●  Use the integer index position to access the mark of the 1st rank student.  

print("Mark of the first rank student is:",marks[0],"(By posiotional index)")

# ●  Use the loc accessor to retrieve the marks of the top 3 ranks by specifying their index labels.

print("Top 3 Ranks are:", ranks.loc['Rank1':'Rank3'],"(By .loc accessor)")

# ● Use the iloc accessor to retrieve the mark of the 3rd-ranked student.

print("Mark of the 3rd rank student is:",ranks.iloc[2],"(By .iloc accessor)")

# ● Apply a boolean mask to filter the Series and retrieve the ranks where the marks are greater than 90.

above_90 = ranks > 90
ranks_above_90 = ranks[above_90]
print("Ranks with marks greater than 90 are:", ranks_above_90, sep="\n")

Mark of the first rank student is: 95 (By posiotional index)
Top 3 Ranks are: Rank1    95
Rank2    92
Rank3    89
dtype: int64 (By .loc accessor)
Mark of the 3rd rank student is: 89 (By .iloc accessor)
Ranks with marks greater than 90 are:
Rank1    95
Rank2    92
dtype: int64


In [28]:
# Manipulating Series:

# ● Modify the mark of the student with the 1st rank to 100.

ranks.loc['Rank1'] = 100
print(ranks.iloc[0])
print(ranks)
print(marks)

# ● Remove the entry corresponding to the last rank from the Series.

ranks = ranks.drop('Rank5')
print(ranks)
print(marks)



100
Rank1    100
Rank2     92
Rank3     89
Rank4     85
Rank5     80
dtype: int64
[95 92 89 85 80]
Rank1    100
Rank2     92
Rank3     89
Rank4     85
dtype: int64
[95 92 89 85 80]


In [29]:
# ● Compute the CGPA by dividing each mark in the Series by 10.

cgpa = ranks / 10
print("\nComputed CGPA:\n", cgpa, sep="")


Computed CGPA:
Rank1    10.0
Rank2     9.2
Rank3     8.9
Rank4     8.5
dtype: float64


## ** Pandas Dataframe **

In [70]:
import pandas as pd

# Define the transaction data
data = {
    'TransactionID':[101, 102, 103, 104, 105, 106, 107, 108, 109, 110], 
    'ProductCategory': ['Electronics', 'Clothing', 'Electronics', 'Furniture', 'Clothing', 
                        'Electronics', 'Furniture', 'Clothing', 'Furniture', 'Electronics'],
    'Region': ['North', 'South', 'North', 'East', 'West', 'North', 'East', 'West', 'South', 'North'],
    'Amount': [200, 150, 300, 450, 200, 250, 300, 180, 350, 400]
}

# Create the DataFrame

transactions = pd.DataFrame(data)
print(transactions)

   TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     150
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200
5            106     Electronics  North     250
6            107       Furniture   East     300
7            108        Clothing   West     180
8            109       Furniture  South     350
9            110     Electronics  North     400


In [71]:
# Data Exploration

# ● Display the transactions DataFrame and its basic information, including head, tail, shape, column names, and data types.

print("Head\n",transactions.head())
print("\nTail\n,",transactions.tail())
print(f"\nDataFrame Shape: {transactions.shape}")
print(f"\nColumn Names: {list(transactions.columns)}")
print("\nDATA TYPES & INFO")
transactions.info() # Displays non-null counts and data types for all columns
 

Head
    TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     150
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200

Tail
,    TransactionID ProductCategory Region  Amount
5            106     Electronics  North     250
6            107       Furniture   East     300
7            108        Clothing   West     180
8            109       Furniture  South     350
9            110     Electronics  North     400

DataFrame Shape: (10, 4)

Column Names: ['TransactionID', 'ProductCategory', 'Region', 'Amount']

DATA TYPES & INFO
<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   TransactionID    10 non-null     int64
 1   ProductCategory  10 non-null     str  
 2   Region           10 no

In [74]:
# ● Display only the 'ProductCategory' and 'Amount' columns.

print(transactions[['ProductCategory', 'Amount']])


  ProductCategory  Amount
0     Electronics     200
1        Clothing     165
2     Electronics     300
3       Furniture     450
4        Clothing     200
5     Electronics     250
6       Furniture     300
7        Clothing     180
8       Furniture     350
9     Electronics     400


In [75]:
# ● Retrieve the last 3 columns of the DataFrame using iloc or loc.

print(transactions.iloc[:,1:])


  ProductCategory Region  Amount
0     Electronics  North     200
1        Clothing  South     165
2     Electronics  North     300
3       Furniture   East     450
4        Clothing   West     200
5     Electronics  North     250
6       Furniture   East     300
7        Clothing   West     180
8       Furniture  South     350
9     Electronics  North     400


In [76]:
# ● Filter rows where the 'Region' is 'North' and 'Amount' is greater than 200. 

filtered_df = transactions[(transactions['Region'] == 'North') & (transactions['Amount'] > 200)]
print(filtered_df)


   TransactionID ProductCategory Region  Amount
2            103     Electronics  North     300
5            106     Electronics  North     250
9            110     Electronics  North     400


In [77]:
# ● Find the value counts for the 'ProductCategory' column.  

print(transactions['ProductCategory'].value_counts())


ProductCategory
Electronics    4
Clothing       3
Furniture      3
Name: count, dtype: int64


In [78]:
# ● Find the unique values in the 'Region' column. 

print(transactions['Region'].unique())


<StringArray>
['North', 'South', 'East', 'West']
Length: 4, dtype: str


In [79]:
# ● Group by 'Region' and find the mean amount for each region.

mean_by_region = transactions.groupby('Region')['Amount'].mean()
print(mean_by_region)

Region
East     375.0
North    287.5
South    257.5
West     190.0
Name: Amount, dtype: float64


In [80]:
# Manipulating the DataFrame:  

# ● Modify the 'Amount' for the transaction with TransactionID 102 to 165.

transactions.loc[transactions['TransactionID'] == 102, 'Amount'] = 165
print(transactions.head(3))


   TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     165
2            103     Electronics  North     300


In [81]:
# ● Add a new column 'Discount' by calculating 10% of the 'Amount'. 

transactions['Discount'] = transactions['Amount'] * 0.10
print("Head\n",transactions.head())


Head
    TransactionID ProductCategory Region  Amount  Discount
0            101     Electronics  North     200      20.0
1            102        Clothing  South     165      16.5
2            103     Electronics  North     300      30.0
3            104       Furniture   East     450      45.0
4            105        Clothing   West     200      20.0

Tail
    TransactionID ProductCategory Region  Amount  Discount
5            106     Electronics  North     250      25.0
6            107       Furniture   East     300      30.0
7            108        Clothing   West     180      18.0
8            109       Furniture  South     350      35.0
9            110     Electronics  North     400      40.0


In [84]:
# ● Remove the row with TransactionID 109.

transactions = transactions.drop(transactions[transactions['TransactionID'] == 109].index)
print(transactions)


   TransactionID ProductCategory Region  Amount  Discount
0            101     Electronics  North     200      20.0
1            102        Clothing  South     165      16.5
2            103     Electronics  North     300      30.0
3            104       Furniture   East     450      45.0
4            105        Clothing   West     200      20.0
5            106     Electronics  North     250      25.0
6            107       Furniture   East     300      30.0
7            108        Clothing   West     180      18.0
9            110     Electronics  North     400      40.0

Tail
    TransactionID ProductCategory Region  Amount  Discount
4            105        Clothing   West     200      20.0
5            106     Electronics  North     250      25.0
6            107       Furniture   East     300      30.0
7            108        Clothing   West     180      18.0
9            110     Electronics  North     400      40.0


In [86]:
# ● Delete the 'Discount' column from the DataFrame.

transactions = transactions.drop(columns=['Discount'])
print(transactions)

   TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     165
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200
5            106     Electronics  North     250
6            107       Furniture   East     300
7            108        Clothing   West     180
9            110     Electronics  North     400
